-- supabase/migrations/003_create_business_events.sql

-- Define un tipo enumerado para los tipos de eventos de negocio, para facilitar las consultas.
CREATE TYPE public.business_event_type AS ENUM (
    'SIGNUP_ATTEMPT',
    'SIGNUP_SUCCESS',
    'SIGNUP_FAILURE',
    'WHATSAPP_TRIAL_AVAILABLE',
    'WHATSAPP_TRIAL_DENIED',
    'OTP_SENT',
    'OTP_VERIFIED',
    'OTP_FAILURE',
    'LOGIN_SUCCESS',
    'LOGIN_FAILURE'
);

-- Crea la tabla para registrar eventos de negocio clave.
CREATE TABLE public.business_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type public.business_event_type NOT NULL,
    -- Claves foráneas para vincular eventos a nuestras entidades principales.
    whatsapp_identity_id BIGINT REFERENCES public.whatsapp_identities(id) ON DELETE SET NULL,
    auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    -- Un campo JSONB flexible para almacenar metadatos relevantes del evento.
    -- Ej: { "error_code": "WHATSAPP_IN_USE", "message": "...", "ip_address": "..." }
    payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Añade comentarios para la documentación de la base de datos.
COMMENT ON TABLE public.business_events IS 'Registra eventos de negocio significativos para observabilidad y auditoría, eliminando la dependencia de logs externos.';
COMMENT ON COLUMN public.business_events.event_type IS 'Clasifica el tipo de evento de negocio que ocurrió.';
COMMENT ON COLUMN public.business_events.payload IS 'Almacena datos contextuales sobre el evento en formato JSON.';

-- Crea índices para optimizar las consultas comunes.
CREATE INDEX idx_event_type ON public.business_events(event_type);
CREATE INDEX idx_event_whatsapp_identity ON public.business_events(whatsapp_identity_id);

-- Habilita Row Level Security, denegando el acceso desde el frontend por defecto.
-- El acceso se gestionará exclusivamente a través de Edge Functions con `service_role`.
ALTER TABLE public.business_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Deny all access from frontend"
ON public.business_events
FOR ALL
USING (false)
WITH CHECK (false);
