-- Create an enum type for the events
CREATE TYPE public.product_event_type AS ENUM (
    'VISIT',
    'LIKE',
    'DISLIKE',
    'ADD_TO_CART'
);

-- Create the product_analytics table
CREATE TABLE public.product_analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id UUID REFERENCES public.stores(id) ON DELETE CASCADE NOT NULL,
    product_id UUID REFERENCES public.products(id) ON DELETE CASCADE,
    event_type public.product_event_type NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    -- A visit is not tied to a specific product, so product_id can be null.
    CONSTRAINT visit_requires_no_product CHECK (
        (event_type = 'VISIT' AND product_id IS NULL) OR (event_type != 'VISIT' AND product_id IS NOT NULL)
    )
);

-- Add indexes for faster queries
CREATE INDEX ON public.product_analytics (store_id);
CREATE INDEX ON public.product_analytics (product_id);
CREATE INDEX ON public.product_analytics (event_type);

-- Enable Row Level Security
ALTER TABLE public.product_analytics ENABLE ROW LEVEL SECURITY;

-- Policies:
-- Data will be inserted via a Supabase Function with the service_role_key
-- and read via an RPC call, so no direct client access is needed.
CREATE POLICY "Deny all access" ON public.product_analytics FOR ALL
USING (false)
WITH CHECK (false);
