-- supabase/migrations/002_create_whatsapp_identities.sql

-- Define un tipo enumerado para el estado del trial, para consistencia y claridad.
CREATE TYPE public.trial_status AS ENUM (
    'TRIAL_AVAILABLE', -- El número es nuevo y puede iniciar un trial.
    'PENDING_VERIFICATION', -- El usuario se ha registrado pero no ha verificado su correo (OTP).
    'TRIAL_ACTIVE',    -- El número está actualmente en un período de prueba.
    'TRIAL_EXPIRED',   -- El número ya ha completado su período de prueba.
    'BLOCKED'          -- El número ha sido bloqueado del servicio.
);

-- Crea la tabla principal para gestionar las identidades de WhatsApp y el estado de sus trials.
CREATE TABLE public.whatsapp_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_number TEXT NOT NULL UNIQUE,
    status public.trial_status NOT NULL DEFAULT 'TRIAL_AVAILABLE',
    trial_started_at TIMESTAMPTZ,
    trial_expires_at TIMESTAMPTZ,
    -- Columna para asociar esta identidad de WhatsApp con un usuario de Supabase Auth.
    -- Es nullable porque un número puede existir en nuestro sistema (ej. bloqueado) sin tener una cuenta de Auth.
    associated_auth_user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Añade comentarios para explicar el propósito de la tabla y las columnas clave.
COMMENT ON TABLE public.whatsapp_identities IS 'Tabla central para la lógica de negocio. Gestiona la identidad primaria (número de WhatsApp), el estado del trial y la asociación con una cuenta de Supabase Auth.';
COMMENT ON COLUMN public.whatsapp_identities.whatsapp_number IS 'Identificador único y primario del vendedor, basado en su número de WhatsApp.';
COMMENT ON COLUMN public.whatsapp_identities.status IS 'Controla el ciclo de vida del trial para un número de WhatsApp.';
COMMENT ON COLUMN public.whatsapp_identities.associated_auth_user_id IS 'Vincula la identidad de negocio (WhatsApp) con la identidad de autenticación (Supabase Auth).';

-- Crea un índice en la columna de número de WhatsApp para búsquedas rápidas.
CREATE INDEX idx_whatsapp_number ON public.whatsapp_identities(whatsapp_number);

-- Crea una función para actualizar automáticamente el campo `updated_at` en cada modificación.
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Asigna el trigger a la tabla para que se ejecute en cada UPDATE.
CREATE TRIGGER on_whatsapp_identities_updated
BEFORE UPDATE ON public.whatsapp_identities
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Habilita Row Level Security (RLS) en la tabla. Por defecto, todo está denegado.
ALTER TABLE public.whatsapp_identities ENABLE ROW LEVEL SECURITY;

-- Política de seguridad: Nadie puede ver los datos de esta tabla desde el frontend.
-- Solo se podrá acceder a través de Edge Functions que se ejecutan con el rol `service_role`.
-- Esto es crucial para proteger la lógica de negocio y los datos de los usuarios.
CREATE POLICY "Deny all access from frontend"
ON public.whatsapp_identities
FOR ALL
USING (false)
WITH CHECK (false);
