name: Set PayPal Secrets

on:
  workflow_dispatch:

jobs:
  set-secrets:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v6
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Set PayPal Secrets
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_ID }}
          PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
          PAYPAL_PLAN_ID_STANDARD: ${{ secrets.PAYPAL_PLAN_ID_STANDARD }}
          PAYPAL_PLAN_ID_FULL: ${{ secrets.PAYPAL_PLAN_ID_FULL }}
          PAYPAL_WEBHOOK_ID: ${{ secrets.PAYPAL_WEBHOOK_ID }}
          PAYPAL_API_URL: ${{ secrets.PAYPAL_API_URL }}
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF
          supabase secrets set \
            PAYPAL_CLIENT_ID=$PAYPAL_CLIENT_ID \
            PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET \
            PAYPAL_PLAN_ID_STANDARD=$PAYPAL_PLAN_ID_STANDARD \
            PAYPAL_PLAN_ID_FULL=$PAYPAL_PLAN_ID_FULL \
            PAYPAL_WEBHOOK_ID=$PAYPAL_WEBHOOK_ID \
            PAYPAL_API_URL=$PAYPAL_API_URL
